### ISSUE TITLE
A function to update package version in `src/rust/Cargo.toml`

### ISSUE THREAD

**Issue by eitsupi** [extendr/rextendr#228]
At the moment I think the version of Cargo.toml is still 0.1.0 unless it is updated manually, should it be updated in general?
If so, it would be useful to be able to update it along with the R package version with a function like `usethis::use_version`.

_Originally posted by @eitsupi in https://github.com/extendr/helloextendr/pull/16#discussion_r1063984447_

**Comment by Ilia-Kosenkov** [comment]
The question is, is there a scenario when the crate version is different from the package version? 
Since rust code could be only a part of the package, I can imagine someone making changes only to R code and not touching Rust code, which might qualify for bumping R package version but keeping crate version unchanged.

**Comment by eitsupi** [comment]
Perhaps this is not valuable enough, so I will close it.
