### ISSUE TITLE
use_extendr_github_action()

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#60]
Probably users want to set up GitHub Actions CI.

**Comment by eitsupi** [comment]
Currently for R4.2 and later, I believe the common R CMD check workflow will work without any additional steps.
Is this issue still necessary?

Although I can think of many useful workflows for Rust-related tools (e.g., one that checks MSRV).

**Comment by Ilia-Kosenkov** [comment]
Hm, what about windows config? One needs to add x86_64-pc-windows-gnu target

**Comment by yutannihilation** [comment]
Oh, good point. `x86_64-pc-windows-gnu` is now installed by default (cf., https://github.com/actions/runner-images/pull/6661). I think we can close this issue.

**Comment by eitsupi** [comment]
Year, since `x86_64-pc-windows-gnu` is added in actions/runner-images#6661, it does not need to be explicitly installed now.

prqlr uses the standard R CMD check workflow, and both builds on R-universe and on CRAN work.
https://github.com/eitsupi/prqlr/blob/238a01bbb7ec1c981012ff6f8cc87869e46a549e/.github/workflows/check.yml

**Comment by Ilia-Kosenkov** [comment]
Cool, feel free to close it since you noticed it first :)

**Comment by yutannihilation** [comment]
Let's close this for now and revisit when some need arises.
